### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-1-infografia-Sandoval6-1#1]
[INFOGRAFIA_CHARLY(1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Sandoval6-1/files/14250156/INFOGRAFIA_CHARLY.1.pdf)

**Comment by saul19bautista** [comment]
excelente trabajo bien estructurado con imagenes entendibles y referentes 
20 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
